### ISSUE TITLE
Unable to load for Floodgate 1.0-Snapshot.

### ISSUE THREAD

**Issue by goosBanny** [rtm516/FloodgatePlaceholders#7]
Using a newer version of PAPI and Floodgate 1.0-Snapshot along with Version 1.1 of FloodgatePlaceholders, the following error appears:
```
[14:43:59 ERROR]: [PlaceholderAPI] Failed to load placeholder expansion from class: com.rtm516.FloodgatePlaceholders.Placeholder
java.lang.NoSuchMethodException: com.rtm516.FloodgatePlaceholders.Placeholder.<init>()
at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_252]
at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_252]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:336) ~[?:?]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:138) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_252]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
at java.util.stream.LongPipeline.reduce(LongPipeline.java:461) ~[?:1.8.0_252]
at java.util.stream.LongPipeline.sum(LongPipeline.java:419) ~[?:1.8.0_252]
at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593) ~[?:1.8.0_252]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288) ~[?:?]
at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1011]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1011]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.5.jar:git-Purpur-1011]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:392) ~[patched_1.16.5.jar:git-Purpur-1011]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1291) ~[patched_1.16.5.jar:git-Purpur-1011]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-Purpur-1011]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1011]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by goosBanny** [comment]
Nevermind, fixed it! Apparently it's supposed to go in the plugins folder!
